drop table if exists USER;
drop table if exists AUTHORIZATION;

CREATE TABLE USERS (
    ID BIGINT AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    ENABLE SMALLINT NOT NULL,
    PRIMARY KEY(USERNAME)
);

CREATE TABLE AUTHORITIES(
    ID BIGINT NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME);
)